name: biruni_universitesi2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.5 # Burada url_launcher ekli kaldı.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
